import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import {
  SYSTEM_INSTRUCTION,
  USER_PROMPT,
  MOCK_YAHOO_NEWS_RESPONSE,
  yahooNewsApiTool,
  slackPosterTool,
} from './constants';

dotenv.config();

const app = express();
const port = process.env.PORT || 3001;

// --- CORS Configuration ---
// Note: In a production environment, it's recommended to restrict the origin
// to the specific domain of your frontend application.
app.use(cors()); 
app.use(express.json());

// --- Gemini AI Initialization ---
if (!process.env.GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY environment variable is not set.");
}
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
const model = "gemini-2.5-flash";

// --- API Endpoints ---
app.get('/api', (req, res) => {
  res.send('Hello from backend!');
});

/**
 * Endpoint to run the main ETL process.
 * It orchestrates the calls to the Gemini API to perform the Extract, Transform, and Load steps.
 */
app.post('/api/run-etl', async (req, res) => {
  console.log('Received request for /api/run-etl');
  try {
    // === Part 1: Initial call to get the first function call (YahooNewsAPI) ===
    console.log('Step 1: Calling Gemini to get news function call...');
    const tools = [{ functionDeclarations: [yahooNewsApiTool, slackPosterTool] }];
    
    let response: GenerateContentResponse = await ai.models.generateContent({
      model,
      contents: { role: 'user', parts: [{ text: USER_PROMPT }] },
      config: {
          systemInstruction: { role: 'model', parts: [{ text: SYSTEM_INSTRUCTION }] },
          tools,
      },
    });

    const firstFunctionCall = response.functionCalls?.[0];
    if (!firstFunctionCall || firstFunctionCall.name !== 'YahooNewsAPI') {
      console.error("Error: Expected a function call to YahooNewsAPI.", response);
      return res.status(500).json({ error: "Expected a function call to YahooNewsAPI, but didn't receive one." });
    }
    console.log('Step 1: Success. Received YahooNewsAPI function call.');

    // === Part 2: Simulate news fetching and send data back to the model ===
    console.log('Step 2: Calling Gemini with mock news data for transformation...');
    const yahooNewsData = MOCK_YAHOO_NEWS_RESPONSE;
    
    const functionResponsePart = {
        functionResponse: {
          name: 'YahooNewsAPI',
          response: {
            content: JSON.stringify(yahooNewsData),
          },
        },
      };
      
    const chatHistory = [
        { role: 'user', parts: [{ text: USER_PROMPT }] },
        { role: 'model', parts: [{ functionCall: firstFunctionCall }] },
    ];

    response = await ai.models.generateContent({
      model,
      contents: [ ...chatHistory, { role: 'function', parts: [ functionResponsePart ] }],
      config: {
          systemInstruction: { role: 'model', parts: [{ text: SYSTEM_INSTRUCTION }] },
          tools,
      },
    });

    const secondFunctionCall = response.functionCalls?.[0];
    if (!secondFunctionCall || secondFunctionCall.name !== 'SlackPoster') {
      console.error("Error: Expected a function call to SlackPoster.", response);
      return res.status(500).json({ error: "Expected a function call to SlackPoster, but didn't receive one." });
    }
    console.log('Step 2: Success. Received SlackPoster function call.');

    // === Part 3: Extract final message and send response to frontend ===
    const slackMessage = secondFunctionCall.args.message;
    if (!slackMessage) {
      console.error("Error: Slack message was not generated by the model.");
      return res.status(500).json({ error: "Slack message was not generated by the model." });
    }
    console.log('Step 3: Success. Extracted Slack message.');

    res.json({
      extract: yahooNewsData,
      transform: {
        description: "Gemini has analyzed the news and generated the final Slack message.",
        functionCall: secondFunctionCall
      },
      load: slackMessage,
    });

  } catch (error) {
    console.error('Error during ETL process:', error);
    res.status(500).json({ error: 'An error occurred during the ETL process.' });
  }
});


app.listen(port, () => {
  console.log(`[server]: Server is running at http://localhost:${port}`);
});